### ISSUE TITLE
Unit tests started failing on the CI

### ISSUE THREAD

**Issue by philipp-classen** [whotracksme/whotracks.me#298]
Possibly related to https://stackoverflow.com/q/73929564/783510

Would be a good time to upgrade Python.

**Comment by philipp-classen** [comment]
That is the error message:

```
Run python -m pip install --upgrade pip
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages (22.2.2)
Collecting certifi==2020.6.20
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
  ...
Requirement already satisfied: pycparser in /opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages (from cffi>=1.12->cryptography->SecretStorage>=3->keyring>=15.1->twine->whotracksme===dev) (2.20)
Installing collected packages: whotracksme
  Running setup.py develop for whotracksme
Successfully installed whotracksme-dev
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.14/x64/bin/whotracksme", line 11, in <module>
    load_entry_point('whotracksme', 'console_scripts', 'whotracksme')()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/runner/work/whotracks.me/whotracks.me/whotracksme/main.py", line 26, in <module>
    from whotracksme.website.builder import Builder
  File "/home/runner/work/whotracks.me/whotracks.me/whotracksme/website/builder.py", line 10, in <module>
    from whotracksme.website.build.home import build_home, build_privacy_policy, build_imprint
  File "/home/runner/work/whotracks.me/whotracks.me/whotracksme/website/build/home.py", line 4, in <module>
    from whotracksme.website.build.companies import company_reach
  File "/home/runner/work/whotracks.me/whotracks.me/whotracksme/website/build/companies.py", line 6, in <module>
    from whotracksme.website.templates import (
  File "/home/runner/work/whotracks.me/whotracks.me/whotracksme/website/templates.py", line 10, in <module>
    import markdown
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/markdown/util.py", line 85, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points().get('markdown.extensions', ())
AttributeError: 'EntryPoints' object has no attribute 'get'
Error: Process completed with exit code 1.
```

**Comment by philipp-classen** [comment]
Upgrading Python to 3.10 makes the tests pass again (see #299 ). But the side-effect of the forced update of libraries is that upgrading plotly is a breaking change and require changes to the html rendering.

**Comment by philipp-classen** [comment]
Fixed now by https://github.com/whotracksme/whotracks.me/pull/299 (has a fix for the pie chart regression, too)
